// CONNEXION - Official Tamil Symposium Connection Question Bank
// Total 72 Curated Questions:
// - Round 1: 10 Core + 10 Backup + 2 Sudden Death = 22 Questions
// - Round 2: 30 Buzzer Questions (10 Group A + 10 Group B + 10 Group C)
// - Round 3: 10 Core + 10 Backup = 20 High-Stakes Championship Questions
// 80% Tamil Pop Culture (Kollywood, Places, Festivals, Politics, Poets, History, Food, Stars)
// 20% Global Icons & Modern Tech (AI, Titans, Global Sports)

export const INITIAL_QUESTIONS = [
  // =========================================================================
  // ROUND 1: CONNECTION CHALLENGE (10 Core Questions)
  // 30s Server Countdown • First to Lock Correct Answer gets Speed Bonus
  // =========================================================================
  {
    id: "r1_q01",
    round: 1,
    type: "text",
    tamilCategory: "Kollywood Blockbuster",
    title: "The Kashmir Bakery Secret",
    prompt: "Connect the 4 clues to identify this Thalapathy Vijay & Lokesh Kanagaraj blockbuster.",
    clues: [
      { id: 1, label: "Clue 1: Cocoa beans & artisan chocolate factory", url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Wild ferocious hyena in snowy mountains", url: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Cozy cafe & bakery in snowy Kashmir", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Fierce hero with curly hair in intense combat", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Leo",
    aliases: ["leo", "leo das", "parthiban", "thalapathy vijay leo", "vijay leo", "bloody sweet"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Leo (2023) features Parthiban running a chocolate cafe in Kashmir, battling a wild hyena, with the reveal of Leo Das ('Bloody Sweet')!"
  },
  {
    id: "r1_q02",
    round: 1,
    type: "text",
    tamilCategory: "Superstar Mass",
    title: "Tiger's Roar",
    prompt: "Connect the 4 clues to name this Nelson Dilipkumar & Superstar Rajinikanth mega blockbuster.",
    clues: [
      { id: 1, label: "Clue 1: Vintage black Ambassador car & wire spectacles", url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Stern retired officer in safari uniform & wire spectacles", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Crown cameos: Shivarajkumar (Narasimha) & Mohanlal (Mathew)", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Blaster speaker & vinyl record pumping bass music", url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Jailer",
    aliases: ["jailer", "tiger muthuvel pandian", "muthuvel pandian", "rajini jailer", "hukum"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Jailer (2023) stars Superstar Rajinikanth as Tiger Muthuvel Pandian, featuring iconic cameos by Shivarajkumar & Mohanlal, with the chartbuster 'Hukum'!"
  },
  {
    id: "r1_q03",
    round: 1,
    type: "text",
    tamilCategory: "Tamil Music Icon",
    title: "The Rockstar Sensation",
    prompt: "Connect the 4 clues to identify this sensational music director ruling Indian cinema.",
    clues: [
      { id: 1, label: "Clue 1: Acoustic soup song recording studio mic", url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Studio keyboard synthesizer & mixing headphones", url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Massive live concerts with screaming arena crowds", url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Gold disc platinum streaming records chartbuster", url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Anirudh Ravichander",
    aliases: ["anirudh", "anirudh ravichander", "ani", "rockstar anirudh"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Anirudh Ravichander debuted with '3' (Why This Kolaveri Di) and has become Kollywood's undisputed Rockstar BGM emperor."
  },
  {
    id: "r1_q04",
    round: 1,
    type: "text",
    tamilCategory: "Kollywood 2024",
    title: "Valour on the Valley",
    prompt: "Connect the 4 clues to name this 2024 blockbuster biographical war film starring Sivakarthikeyan.",
    clues: [
      { id: 1, label: "Clue 1: Indian Army 44 Rashtriya Rifles camouflage uniform", url: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Snowbound peaks & Shopian anti-terror operation", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Emotional reunion and military farewell ceremony", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Gallantry medal ribbon of honor & valor", url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Amaran",
    aliases: ["amaran", "major mukund", "major mukund varadarajan", "mukund varadarajan", "sivakarthikeyan amaran"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Amaran (2024), directed by Rajkumar Periasamy and produced by Kamal Haasan, honors the real-life bravery of Major Mukund Varadarajan AC."
  },
  {
    id: "r1_q05",
    round: 1,
    type: "text",
    tamilCategory: "Tamil Legend",
    title: "The Missile Man of India",
    prompt: "Connect the 4 clues to name this legendary visionary, scientist, and former President born in Tamil Nadu.",
    clues: [
      { id: 1, label: "Clue 1: Pamban Sea Bridge & coastal Rameswaram island", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Agni & Prithvi aerospace ballistic missiles", url: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Rashtrapati Bhavan — 11th President of India", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: 'Wings of Fire' & 'Ignited Minds' youth books", url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "A. P. J. Abdul Kalam",
    aliases: ["abdul kalam", "dr abdul kalam", "apj abdul kalam", "a p j abdul kalam", "dr apj abdul kalam", "kalam", "missile man"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Dr. A. P. J. Abdul Kalam was born in Rameswaram, led India's missile program, and inspired millions worldwide as the People's President."
  },
  {
    id: "r1_q06",
    round: 1,
    type: "text",
    tamilCategory: "Tamil Comedy Icon",
    title: "Vaigai Puyal",
    prompt: "Connect the 4 clues to identify the undisputed king of Tamil comedy memes and dialogues.",
    clues: [
      { id: 1, label: "Clue 1: Yellow construction helmet & hammer (Contractor Naesamani)", url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Dubai return Kaipulla & iconic sunglasses", url: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: 'Ahaa Enna Porutham' / Vandumurugan advocate", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Royal crown & palace of King 23am Pulikesi", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Vadivelu",
    aliases: ["vadivelu", "vaigai puyal", "vaigai puyal vadivelu", "naesamani", "contractor naesamani", "kaipulla"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Vadivelu (Vaigai Puyal) created timeless cultural icons like Contractor Naesamani (#PrayForNaesamani), Kaipulla, and Imsai Arasan 23am Pulikesi!"
  },
  {
    id: "r1_q07",
    round: 1,
    type: "text",
    tamilCategory: "Tamil Cult Classic",
    title: "Chellom & Kabaddi",
    prompt: "Connect the 4 clues to name this 2004 Thalapathy Vijay sports action film that broke re-release box office records in 2024.",
    clues: [
      { id: 1, label: "Clue 1: Kabaddi court line markings & championship trophy", url: "https://images.unsplash.com/photo-1526676037777-05a232554f77?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Chennai Marina Beach Lighthouse & coastal wind", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Prakash Raj as Muthupandi whispering 'Chellom...'", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Vidyasagar's energetic 'Appadi Podu' and Otteri Nari", url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Ghilli",
    aliases: ["ghilli", "gilli", "velu ghilli", "vijay ghilli", "chellom"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Ghilli (2004) starring Thalapathy Vijay, Trisha, and Prakash Raj as Muthupandi is one of Kollywood's highest grossing cult re-releases of all time!"
  },
  {
    id: "r1_q08",
    round: 1,
    type: "text",
    tamilCategory: "Tamil Global Titan (Tech)",
    title: "Madurai to Mountain View",
    prompt: "Connect the 4 clues to name this Tamil-born leader who heads the world's most valuable search engine empire.",
    clues: [
      { id: 1, label: "Clue 1: Madurai roots & Chennai Vanavani School in IIT campus", url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: IIT Kharagpur Metallurgical Engineering alum", url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Google Chrome browser creation & launch (2008)", url: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Global Chief Executive Officer of Alphabet & Google", url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Sundar Pichai",
    aliases: ["sundar pichai", "pichai", "sundar", "sundararajan pichai"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Sundar Pichai was born in Madurai, raised in Chennai, led the creation of Google Chrome, and is now the CEO of Alphabet & Google."
  },
  {
    id: "r1_q09",
    round: 1,
    type: "text",
    tamilCategory: "Tamil Sports Legend",
    title: "The Grandmaster from Chennai",
    prompt: "Connect the 4 clues to identify this Chennai teenage prodigy who made history in world chess.",
    clues: [
      { id: 1, label: "Clue 1: 64-square black and white chess board with Knights & Kings", url: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: 44th FIDE Chess Olympiad in Chennai (Thambi mascot)", url: "https://images.unsplash.com/photo-1586165368502-1bad197a6461?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Winner of FIDE Candidates Tournament 2024 in Toronto", url: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Youngest World Chess Championship challenger at age 17", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "D. Gukesh",
    aliases: ["gukesh", "d gukesh", "gukesh d", "dommaraju gukesh", "d. gukesh"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Chennai's D. Gukesh became the youngest challenger in World Chess Championship history after winning the 2024 Candidates Tournament!"
  },
  {
    id: "r1_q10",
    round: 1,
    type: "text",
    tamilCategory: "Global Tech Phenomenon",
    title: "The Generative Brain",
    prompt: "Connect the 4 clues to name this revolutionary conversational generative AI system developed by OpenAI.",
    clues: [
      { id: 1, label: "Clue 1: Deep neural network synapses & artificial neural weights", url: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: OpenAI circular geometric green/black spiral logo", url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Text prompt input box generating answers, code & poetry", url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Sam Altman & transformer LLM architecture", url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "ChatGPT",
    aliases: ["chatgpt", "chat gpt", "openai", "gpt", "artificial intelligence", "generative ai"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "ChatGPT, created by OpenAI, ignited the worldwide generative AI wave, transforming coding, education, and creative writing."
  },

  // =========================================================================
  // ROUND 1: BACKUP QUESTIONS (10 Backup Questions for Shuffling)
  // =========================================================================
  {
    id: "r1_q11",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Grand Festival",
    title: "Harvest of Joy",
    prompt: "Connect the 4 clues to identify this supreme 4-day Tamil harvest festival celebrating nature and Sun God.",
    clues: [
      { id: 1, label: "Clue 1: Tall purple sugarcane stalks & fresh turmeric bunch", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Decorated earthen clay pot boiling over sweet milk rice", url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Valiant youth embracing roaring bulls in Alanganallur Jallikattu", url: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Jubilant harvest chant welcoming the auspicious Tamil Thai month", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Pongal",
    aliases: ["pongal", "thai pongal", "jallikattu", "mattu pongal", "boghi"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Pongal is Tamil Nadu's signature harvest festival celebrated over 4 days with sweet rice overflowing from clay pots, sugarcane, and Jallikattu!"
  },
  {
    id: "r1_q12",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Poet & Sage",
    title: "133 Couplets of Wisdom",
    prompt: "Connect the 4 clues to identify this revered Tamil poet-philosopher whose ethical treatise guides humanity.",
    clues: [
      { id: 1, label: "Clue 1: 133-foot colossal granite statue in Kanyakumari ocean", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Ancient palm leaf manuscripts (Olai Chuvadi) & iron stylus", url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: 1330 sacred couplets divided into Aram, Porul, and Inbam", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Valluvar Kottam chariot monument in Nungambakkam, Chennai", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Thiruvalluvar",
    aliases: ["thiruvalluvar", "valluvar", "thirukkural", "saint thiruvalluvar"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Thiruvalluvar authored the Thirukkural consisting of 1330 rhyming couplets across 133 chapters, celebrated with a 133-foot statue at Kanyakumari."
  },
  {
    id: "r1_q13",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Nationalist Poet",
    title: "Mahakavi of Fire and Freedom",
    prompt: "Connect the 4 clues to identify this passionate revolutionary poet who awakened the Indian independence movement.",
    clues: [
      { id: 1, label: "Clue 1: Signature white turban (Mundasu) & piercing fierce eyes with twirled mustache", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: 'Achamillai Achamillai Acham Enbathillaye' fiery verses", url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Ettayapuram birthplace & exile in French Pondicherry", url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Songs championing women empowerment ('Pudhumai Penn')", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Subramania Bharati",
    aliases: ["bharathiyar", "bharathi", "subramania bharati", "mahakavi bharathiyar", "subramanya bharathi", "mundasu kavi"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Mahakavi Subramania Bharati was a pioneer of modern Tamil poetry whose patriotic and progressive poems energized India's freedom struggle."
  },
  {
    id: "r1_q14",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Statesman & Leader",
    title: "The Kingmaker & Educational Pioneer",
    prompt: "Connect the 4 clues to name this iconic Chief Minister revered as 'Kalvi Kan Thirandha Kaamaraasar'.",
    clues: [
      { id: 1, label: "Clue 1: Simple handspun Khadi white shirt & dhoti lifestyle", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Free midday meals bringing lakhs of rural children to school", url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Virudhunagar hometown roots & Congress President Kingmaker", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Posthumous Bharat Ratna & major dams across Tamil Nadu", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Kamarajar",
    aliases: ["kamarajar", "k kamaraj", "kamaraj", "perunthalaivar kamarajar", "karma veerar kamarajar"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Perunthalaivar K. Kamaraj served as Chief Minister of Tamil Nadu (1954–1963), opened thousands of schools, and pioneered the free mid-day meal scheme."
  },
  {
    id: "r1_q15",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Heritage City",
    title: "The Sleepless City of Jasmine & Temples",
    prompt: "Connect the 4 clues to identify this ancient heritage city situated on the banks of River Vaigai.",
    clues: [
      { id: 1, label: "Clue 1: Soaring colorful sculpted towers of Meenakshi Amman Temple", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Fragrant GI-tagged fresh white Jasmine flower garlands", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Chilled badam pisin sweet Jigarthanda drink stall", url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Thoonga Nagaram midnight food streets & Thirumalai Nayakkar Palace", url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Madurai",
    aliases: ["madurai", "thoonga nagaram", "temple city madurai", "kadambavanam"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Madurai, known as Thoonga Nagaram (City that Never Sleeps), is famous for the historic Meenakshi Temple, Madurai Malli, and Jigarthanda."
  },
  {
    id: "r1_q16",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Architectural Wonder",
    title: "The 1000-Year Granite Marvel",
    prompt: "Connect the 4 clues to name this UNESCO World Heritage Chola monument whose shadow never falls at noon.",
    clues: [
      { id: 1, label: "Clue 1: Raja Raja Cholan I royal inscription in Tamil Brahmi", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: 80-tonne single monolithic granite cupola capstone at apex", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Giant monolithic Nandi statue carved out of a single rock", url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Fertile Cauvery delta river breeze & Periya Kovil majestic tower", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Brihadisvara Temple",
    aliases: ["brihadisvara temple", "thanjavur periya kovil", "thanjavur big temple", "big temple", "periya kovil", "thanjavur temple"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Thanjavur Brihadisvara Temple (Periya Kovil) was consecrated in 1010 CE by Raja Raja Chola I and is renowned for its 80-tonne monolithic granite Vimana."
  },
  {
    id: "r1_q17",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil History & Freedom Fighter",
    title: "Veeramangai of Sivaganga",
    prompt: "Connect the 4 clues to name the first Indian queen who waged war and defeated the British East India Company.",
    clues: [
      { id: 1, label: "Clue 1: Sivaganga royal palace & fierce traditional Silambam bamboo staff", url: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Curved Valari throwing weapon & battle sword", url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Commander Kuyili leading the world's first suicide bomber attack", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Recaptured her kingdom from the British in 1780 CE", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Rani Velu Nachiyar",
    aliases: ["velu nachiyar", "rani velu nachiyar", "veeramangai velu nachiyar", "velunachiyar"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Veeramangai Rani Velu Nachiyar was queen of Sivaganga and the first Indian sovereign to successfully defeat British colonial forces, regaining her throne in 1780."
  },
  {
    id: "r1_q18",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Politics & Cinema 2024",
    title: "The Lion & Fighting Elephants Flag",
    prompt: "Connect the 4 clues to identify this political party formed in 2024 that held a mammoth conference in Vikravandi.",
    clues: [
      { id: 1, label: "Clue 1: Two fighting tusked elephants flanking the sacred Vaagai flower", url: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Bicolour flag with vibrant maroon-red top/bottom and bright yellow centre", url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Massive maiden state conference attended by lakhs in V. Salai, Vikravandi", url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Founded and led by actor Thalapathy Vijay", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Tamilaga Vettri Kazhagam",
    aliases: ["tvk", "tamilaga vettri kazhagam", "thalapathy tvk", "vijay party tvk", "tamizhaga vetri kazhagam"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Tamilaga Vettri Kazhagam (TVK) was founded in February 2024 by Thalapathy Vijay, unveiling its elephant-and-vaagai flag and ideological manifesto."
  },
  {
    id: "r1_q19",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Tamil Geographic Landmark",
    title: "Confluence of Three Oceans",
    prompt: "Connect the 4 clues to identify the southernmost tip of mainland India located in Tamil Nadu.",
    clues: [
      { id: 1, label: "Clue 1: Triveni Sangam where Indian Ocean, Arabian Sea & Bay of Bengal meet", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Vivekananda Rock Memorial & meditation hall amidst crashing waves", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Sunset and full moon rise visible at the exact same moment on horizon", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Multi-colored shoreline sands & Gandhi Memorial mandapam", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Kanyakumari",
    aliases: ["kanyakumari", "cape comorin", "kanniyakumari"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Kanyakumari is the southernmost coastal point of mainland India, famed for the meeting of three seas, Vivekananda Rock, and panoramic sunsets."
  },
  {
    id: "r1_q20",
    round: 1,
    isBackup: true,
    type: "text",
    tamilCategory: "Global Pop Culture (20% World)",
    title: "Genius, Billionaire, Playboy, Philanthropist",
    prompt: "Connect the 4 clues to identify this Marvel superhero powered by an Arc Reactor in his chest.",
    clues: [
      { id: 1, label: "Clue 1: Glowing blue fusion Arc Reactor mounted in chest", url: "https://images.unsplash.com/photo-1517976487502-588383a8b27f?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Hot-rod red and gold powered robotic exoskeleton armor suit", url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: JARVIS artificial intelligence voice assistant", url: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Armored hero with glowing chest arc reactor snapping the Infinity Stones", url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Iron Man",
    aliases: ["iron man", "tony stark", "ironman", "stark"],
    points: 10,
    speedBonus: 5,
    penalty: 0,
    explanation: "Iron Man (Tony Stark), portrayed by Robert Downey Jr., kicked off the Marvel Cinematic Universe and sacrificed himself with the iconic nano-gauntlet snap."
  },

  // =========================================================================
  // ROUND 1: SUDDEN DEATH TIEBREAKERS (2 Questions)
  // Triggered only if there is a tie at the Rank 15 cutoff
  // =========================================================================
  {
    id: "r1_sd01",
    round: 1,
    isSuddenDeath: true,
    type: "text",
    tamilCategory: "Tamil Cinema Universe",
    title: "Sudden Death Tiebreaker #1: The Cinematic Universe",
    prompt: "Connect the 4 clues to name this interconnected Tamil film universe created by director Lokesh Kanagaraj.",
    clues: [
      { id: 1, label: "Clue 1: Dilli eating huge bucket of Biryani in prison (Kaithi)", url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Ghost mask & Gatling machine gun battle (Vikram)", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Kashmir chocolate cafe & hyena encounter (Leo)", url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: Rolex gold watch with scorpion emblem", url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "LCU",
    aliases: ["lcu", "lokesh cinematic universe", "lokesh kanagaraj universe", "lokesh universe"],
    points: 15,
    speedBonus: 5,
    penalty: 0,
    explanation: "The Lokesh Cinematic Universe (LCU) unites Kaithi, Vikram, and Leo with recurring characters, Biryani, guns, and Rolex!"
  },
  {
    id: "r1_sd02",
    round: 1,
    isSuddenDeath: true,
    type: "text",
    tamilCategory: "Tamil Music Legend",
    title: "Sudden Death Tiebreaker #2: Mozart of Madras",
    prompt: "Connect the 4 clues to name this two-time Oscar-winning Tamil composer revered worldwide.",
    clues: [
      { id: 1, label: "Clue 1: Debut cassette 'Roja' in 1992 under Mani Ratnam", url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Two Academy Award Golden Oscar statuettes for Slumdog Millionaire", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: KM Music Conservatory in Kodambakkam, Chennai", url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80" },
      { id: 4, label: "Clue 4: 'Ella Pugazhum Iraivanukke' iconic speech", url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "A. R. Rahman",
    aliases: ["ar rahman", "a r rahman", "rahman", "arr", "mozart of madras"],
    points: 15,
    speedBonus: 5,
    penalty: 0,
    explanation: "A. R. Rahman transformed Indian film music with Roja, won 2 Oscars & Grammys, and established Chennai's KM Music Conservatory."
  },

  // =========================================================================
  // ROUND 2: LIVE SPEED BUZZER — 30 QUESTIONS (10 Group A + 10 Group B + 10 Group C)
  // Fastest Buzz Locks Out Others • Correct +20 pts, Wrong -5 pts
  // =========================================================================

  // ------------------------- GROUP A (10 Questions) -------------------------
  {
    id: "r2_ga_01",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Kollywood 2022",
    title: "Group A — Buzzer Clue 1",
    prompt: "BUZZ IN! Connect: Ghost vigilante black hoodie, Amar police team, Biryani, Rolex scorpion watch.",
    clues: [
      { id: 1, label: "Clue 1: Masked black hoodie vigilante (Ghost)", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Rolex luxury gold watch with scorpion engraving", url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Vikram",
    aliases: ["vikram", "kamal haasan vikram", "vikram 2022", "rolex vikram"],
    points: 20,
    penalty: 5,
    explanation: "Vikram (2022) starring Kamal Haasan, Fahadh Faasil, Vijay Sethupathi, and Suriya as Rolex broke Kollywood box office records!"
  },
  {
    id: "r2_ga_02",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Tamil Music Icon",
    title: "Group A — Buzzer Clue 2",
    prompt: "BUZZ IN! Connect: Pudhupettai BGM, 7G Rainbow Colony violin, Ilaiyaraaja's legacy, 'U1 Drug'.",
    clues: [
      { id: 1, label: "Clue 1: Melancholic violin solo & deep cinematic acoustic bass", url: "https://images.unsplash.com/photo-1612225330812-01a9c6b355ec?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Retro audio cassette tape marked 'U1 Drug'", url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Yuvan Shankar Raja",
    aliases: ["yuvan", "yuvan shankar raja", "u1", "u1 drug", "ysr"],
    points: 20,
    penalty: 5,
    explanation: "Yuvan Shankar Raja (U1) is celebrated by Tamil youth for his soul-stirring BGMs and songs in Pudhupettai, Mankatha, and GOAT."
  },
  {
    id: "r2_ga_03",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Namma Ooru Culture",
    title: "Group A — Buzzer Clue 3",
    prompt: "BUZZ IN! Connect: Marina Beach promenade, Central Station clock tower, Filter coffee in brass Davarah.",
    clues: [
      { id: 1, label: "Clue 1: Marina Beach sunset shoreline & evening breeze", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Steaming hot South Indian filter coffee in brass Davarah", url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Chennai",
    aliases: ["chennai", "madras", "namma chennai", "singara chennai"],
    points: 20,
    penalty: 5,
    explanation: "Chennai (Madras) is defined by its iconic Marina Beach, heritage railway architecture, filter coffee, and vibrant culture!"
  },
  {
    id: "r2_ga_04",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Kollywood Action Thriller",
    title: "Group A — Buzzer Clue 4",
    prompt: "BUZZ IN! Connect: DIA Army Captain Jagdish, 12-sleeper-cells shootout, Mumbai suburban trains, Vidyut Jammwal.",
    clues: [
      { id: 1, label: "Clue 1: Army Captain uniform with Defense Intelligence dog tag", url: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: 12 coins placed on a table representing sleeper cell targets", url: "https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Thuppakki",
    aliases: ["thuppakki", "thuppaki", "vijay thuppakki", "jagadish"],
    points: 20,
    penalty: 5,
    explanation: "Thuppakki (2012), directed by AR Murugadoss starring Thalapathy Vijay, revolutionized Indian military thrillers with the iconic 12 sleeper-cell operation!"
  },
  {
    id: "r2_ga_05",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Tamil Social Reformer",
    title: "Group A — Buzzer Clue 5",
    prompt: "BUZZ IN! Connect: Black shirt, Self-Respect Movement, Rationalism & anti-caste struggle, Erode roots.",
    clues: [
      { id: 1, label: "Clue 1: Black shirt & long flowing white beard of rationalism", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Kudi Arasu journal printing press & equality banners", url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Periyar E. V. Ramasamy",
    aliases: ["periyar", "thanthai periyar", "periyar ev ramasamy", "e v ramasamy", "evr"],
    points: 20,
    penalty: 5,
    explanation: "Thanthai Periyar founded the Self-Respect Movement and Dravidar Kazhagam, pioneering women's equality, rationalism, and social justice across Tamil Nadu."
  },
  {
    id: "r2_ga_06",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Tamil Music Maestro",
    title: "Group A — Buzzer Clue 6",
    prompt: "BUZZ IN! Connect: Pannaipuram harmonium, 1000+ film scores, Royal Philharmonic Orchestra London, 'Isaignani'.",
    clues: [
      { id: 1, label: "Clue 1: Traditional reed Harmonium keys & white veshti", url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Western classical grand symphony orchestra scoresheet", url: "https://images.unsplash.com/photo-1612225330812-01a9c6b355ec?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Ilaiyaraaja",
    aliases: ["ilaiyaraaja", "ilayaraja", "isaignani", "maestro ilaiyaraaja", "isaignani ilaiyaraaja"],
    points: 20,
    penalty: 5,
    explanation: "Isaignani Ilaiyaraaja composed music for over 1,000 films, fusing Tamil folk traditions with Western classical polyphony."
  },
  {
    id: "r2_ga_07",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Tamil Sacred Festival",
    title: "Group A — Buzzer Clue 7",
    prompt: "BUZZ IN! Connect: Thiruvannamalai holy mountain, Giant brass cauldron, Millions of earthen clay lamps, Agni element.",
    clues: [
      { id: 1, label: "Clue 1: Glowing terracotta Agal Vilakku oil lamps lighting up balconies", url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Massive cauldron flame atop the sacred Annamalaiyar hill peak", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Karthigai Deepam",
    aliases: ["karthigai deepam", "karthigai", "thiruvannamalai deepam", "maha deepam"],
    points: 20,
    penalty: 5,
    explanation: "Karthigai Deepam is one of Tamil Nadu's oldest festivals, celebrated with lamps across homes and the legendary Maha Deepam atop Thiruvannamalai hill."
  },
  {
    id: "r2_ga_08",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Tamil Freedom Legend",
    title: "Group A — Buzzer Clue 8",
    prompt: "BUZZ IN! Connect: Swadeshi steamships, Tuticorin to Colombo merchant line, Pulling the heavy prison oil mill.",
    clues: [
      { id: 1, label: "Clue 1: Historic steamships sailing between Tuticorin and Colombo", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Heavy stone prison oil-press (Chekku) pulled by an iron-willed patriot", url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "V. O. Chidambaram Pillai",
    aliases: ["voc", "v o chidambaram pillai", "kappalottiya thamizhan", "v o c", "chidambaram pillai"],
    points: 20,
    penalty: 5,
    explanation: "V. O. Chidambaram Pillai (Kappalottiya Thamizhan) launched India's first indigenous shipping service to break British monopoly and endured brutal prison labor."
  },
  {
    id: "r2_ga_09",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Tamil Comedy Legends",
    title: "Group A — Buzzer Clue 9",
    prompt: "BUZZ IN! Connect: The two-banana dilemma ('Intha vazhaipazham enga?'), Petromax light dialogue, Classic banter duo.",
    clues: [
      { id: 1, label: "Clue 1: Two yellow ripe bananas in a village tea stall", url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Vintage brass kerosene Petromax pressure lamp ('Petromax light-e thaan venuma?')", url: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Goundamani and Senthil",
    aliases: ["goundamani and senthil", "goundamani senthil", "goundamani", "senthil", "vazhaipazham comedy"],
    points: 20,
    penalty: 5,
    explanation: "Goundamani & Senthil are Kollywood's gold standard comedy pair, whose 'Vazhaipazham' and 'Petromax Light' gags remain unmatched evergreen pop-culture memes."
  },
  {
    id: "r2_ga_10",
    round: 2,
    group: "A",
    type: "buzzer",
    tamilCategory: "Global Sports Legend",
    title: "Group A — Buzzer Clue 10",
    prompt: "BUZZ IN! Connect: Albiceleste #10 jersey, 2022 Qatar World Cup golden trophy, 8 Ballon d'Or awards, Left-foot wizard.",
    clues: [
      { id: 1, label: "Clue 1: Sky blue and white striped football jersey with #10", url: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Solid gold FIFA World Cup trophy being kissed in Qatar 2022", url: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Lionel Messi",
    aliases: ["messi", "lionel messi", "leo messi", "king messi"],
    points: 20,
    penalty: 5,
    explanation: "Lionel Messi led Argentina to victory in the 2022 World Cup, cementing his status as one of football's greatest of all time with 8 Ballon d'Or titles."
  },

  // ------------------------- GROUP B (10 Questions) -------------------------
  {
    id: "r2_gb_01",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Kollywood Classic",
    title: "Group B — Buzzer Clue 1",
    prompt: "BUZZ IN! Connect: 500 Crores cricket betting money, Salt & Pepper hairstyle, Vinayak Mahadev, 'Money Money Money'.",
    clues: [
      { id: 1, label: "Clue 1: Stacks of betting cash currency notes in metallic suitcases", url: "https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Playing cards Ace of Spades & dark sunglasses", url: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Mankatha",
    aliases: ["mankatha", "mangatha", "vinayak mahadev", "ajith mankatha", "thala mankatha"],
    points: 20,
    penalty: 5,
    explanation: "Mankatha (2011), directed by Venkat Prabhu, starred Thala Ajith Kumar as corrupt cop Vinayak Mahadev stealing 500 Crores!"
  },
  {
    id: "r2_gb_02",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Tamil Science Pride",
    title: "Group B — Buzzer Clue 2",
    prompt: "BUZZ IN! Connect: Lunar South Pole landing, ISRO Vikram lander, Project Director Dr. P. Veeramuthuvel from Viluppuram.",
    clues: [
      { id: 1, label: "Clue 1: Golden lunar rover exploring moon's cratered surface", url: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: ISRO Mission Operations Complex celebrating touchdown", url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Chandrayaan-3",
    aliases: ["chandrayaan 3", "chandrayaan-3", "chandrayaan", "veeramuthuvel", "isro chandrayaan"],
    points: 20,
    penalty: 5,
    explanation: "Chandrayaan-3 made India the first nation to land on the Moon's South Pole, led by Project Director Dr. P. Veeramuthuvel from Viluppuram, Tamil Nadu."
  },
  {
    id: "r2_gb_03",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Tamil Cinema & Food",
    title: "Group B — Buzzer Clue 3",
    prompt: "BUZZ IN! Connect: Madurai cool rose milk almond drink, Assault Sethu gangster, Vintage 16mm movie camera.",
    clues: [
      { id: 1, label: "Clue 1: Madurai famous sweet dessert drink with badam pisin & ice cream", url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Retro 1970s wooden film camera reel & clapperboard", url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Jigarthanda",
    aliases: ["jigarthanda", "jigarthanda doublex", "assault sethu", "karthik subbaraj jigarthanda"],
    points: 20,
    penalty: 5,
    explanation: "Karthik Subbaraj's Jigarthanda and Jigarthanda DoubleX connect the famous Madurai sweet drink with cinema-making gangsters!"
  },
  {
    id: "r2_gb_04",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Tamil Political Titan",
    title: "Group B — Buzzer Clue 4",
    prompt: "BUZZ IN! Connect: Fur cap & dark sunglasses, Rickshawkaaran bell, Puratchi Thalaivar, Midday meals.",
    clues: [
      { id: 1, label: "Clue 1: Iconic white fur cap and rectangular dark sunglasses", url: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Two leaves (Irattai Ilai) political symbol & massive public rallies", url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "M. G. Ramachandran",
    aliases: ["mgr", "mg ramachandran", "m.g.r", "puratchi thalaivar", "puratchi thalaivar mgr"],
    points: 20,
    penalty: 5,
    explanation: "M. G. Ramachandran (MGR) was a matinee idol turned 3-time Chief Minister who founded the AIADMK and expanded nutritious school meals."
  },
  {
    id: "r2_gb_05",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Tamil Heritage Wonder",
    title: "Group B — Buzzer Clue 5",
    prompt: "BUZZ IN! Connect: Shore Temple by sea, Arjuna's Penance rock carving, Krishna's Butter Ball, Pallava dynasty.",
    clues: [
      { id: 1, label: "Clue 1: Sea-facing ancient rock-cut Shore Temple with stone pillars", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Massive 250-tonne boulder precariously perched on a steep slope", url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Mahabalipuram",
    aliases: ["mahabalipuram", "mamallapuram", "shore temple mahabalipuram"],
    points: 20,
    penalty: 5,
    explanation: "Mahabalipuram (Mamallapuram) is a 7th-century coastal port city of the Pallavas famous for its monolithic rock rathas, Shore Temple, and Krishna's Butter Ball."
  },
  {
    id: "r2_gb_06",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Kollywood Blockbuster",
    title: "Group B — Buzzer Clue 6",
    prompt: "BUZZ IN! Connect: Prisoner Dilli driving lorry, Bucket of Biryani, Gatling gun shooting at police station.",
    clues: [
      { id: 1, label: "Clue 1: A massive bucket of hot chicken Biryani eaten hungrily with bare hands", url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Heavy freight lorry racing through dark jungle roads with no songs or heroine", url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Kaithi",
    aliases: ["kaithi", "dilli kaithi", "karthi kaithi", "kaidhi"],
    points: 20,
    penalty: 5,
    explanation: "Kaithi (2019) directed by Lokesh Kanagaraj starred Karthi as prisoner Dilli, kickstarting the blockbuster Lokesh Cinematic Universe (LCU)!"
  },
  {
    id: "r2_gb_07",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Tamil Ancient Literature",
    title: "Group B — Buzzer Clue 7",
    prompt: "BUZZ IN! Connect: Grandma poet with walking stick, Athichoodi moral alphabets, Rare immortality gooseberry (Nellikani).",
    clues: [
      { id: 1, label: "Clue 1: Wooden walking stick & venerable grandmother scholar figure", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Green sour gooseberry (Nellikani) presented by King Athiyaman", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Avvaiyar",
    aliases: ["avvaiyar", "auvaiyar", "athichoodi avvaiyar", "avvai"],
    points: 20,
    penalty: 5,
    explanation: "Avvaiyar is the beloved ancient Tamil woman poet whose works like Athichoodi and Konraiventhan teach timeless ethical maxims to children."
  },
  {
    id: "r2_gb_08",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Tamil Comedy Star",
    title: "Group B — Buzzer Clue 8",
    prompt: "BUZZ IN! Connect: Lollu Sabha spoof television, Lightning fast counter punches, Boss Engira Bhaskaran 'Nanba'.",
    clues: [
      { id: 1, label: "Clue 1: Television studio parody comedy set (Lollu Sabha)", url: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Modern coaching tuition institute board ('Nalla Nanban')", url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Santhanam",
    aliases: ["santhanam", "actor santhanam", "santa", "lollu sabha santhanam"],
    points: 20,
    penalty: 5,
    explanation: "Santhanam gained fame through Vijay TV's Lollu Sabha before dominating 2010s Kollywood comedy alongside Arya, Simbu, and Udhayanidhi."
  },
  {
    id: "r2_gb_09",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Tamil Culinary Pride",
    title: "Group B — Buzzer Clue 9",
    prompt: "BUZZ IN! Connect: Thamirabarani perennial river water, Ghee-dripping dark wheat dessert, Iruttu Kadai shop.",
    clues: [
      { id: 1, label: "Clue 1: Pure crystal Thamirabarani river water flowing through southern hills", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Glossy warm rich wheat ghee sweet wrapped in fresh green plantain leaf", url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Tirunelveli Halwa",
    aliases: ["tirunelveli halwa", "nellai halwa", "iruttu kadai halwa", "halwa"],
    points: 20,
    penalty: 5,
    explanation: "Tirunelveli Halwa is world-famous for its silky texture made from fermented wheat milk, pure ghee, and the distinct sweet waters of the Thamirabarani River."
  },
  {
    id: "r2_gb_10",
    round: 2,
    group: "B",
    type: "buzzer",
    tamilCategory: "Global Tech Pioneer",
    title: "Group B — Buzzer Clue 10",
    prompt: "BUZZ IN! Connect: Bitten Apple logo, Black turtleneck & round glasses, 'One More Thing...', iPhone revolution.",
    clues: [
      { id: 1, label: "Clue 1: Minimalist monochrome silhouette of an apple with a bite mark", url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Hand holding the original glass-screen smartphone keynote slide (2007)", url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Steve Jobs",
    aliases: ["steve jobs", "jobs", "apple steve jobs"],
    points: 20,
    penalty: 5,
    explanation: "Steve Jobs co-founded Apple, revolutionizing personal computing, animated movies (Pixar), and modern smartphones with the iPhone."
  },

  // ------------------------- GROUP C (10 Questions) -------------------------
  {
    id: "r2_gc_01",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Historical Epic",
    title: "Group C — Buzzer Clue 1",
    prompt: "BUZZ IN! Connect: Chola dynasty royal tiger emblem, Vanthiyathevan horse journey, Nandhini conspiracy, Kalki novel.",
    clues: [
      { id: 1, label: "Clue 1: Imperial golden tiger banner & ancient bronze war armor", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Galloping white horse crossing river & Thanjavur fortress", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Ponniyin Selvan",
    aliases: ["ponniyin selvan", "ps1", "ps2", "chola", "kalki ponniyin selvan", "aditha karikalan"],
    points: 20,
    penalty: 5,
    explanation: "Mani Ratnam's Ponniyin Selvan (PS-1 & PS-2) adapted Kalki's monumental novel about the golden Chola empire."
  },
  {
    id: "r2_gc_02",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Megastar",
    title: "Group C — Buzzer Clue 2",
    prompt: "BUZZ IN! Connect: Vijay TV anchor mic, Remo nurse avatar, Doctor scalpel, Amaran military uniform.",
    clues: [
      { id: 1, label: "Clue 1: TV host microphone & stand-up mimicry stage", url: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Stethoscope & Army camouflage commander cap", url: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Sivakarthikeyan",
    aliases: ["sivakarthikeyan", "sk", "siva karthikeyan", "prince sk"],
    points: 20,
    penalty: 5,
    explanation: "Sivakarthikeyan rose from Vijay TV mimicry contestant to anchor, then to box-office king with hits like Remo, Doctor, and Amaran!"
  },
  {
    id: "r2_gc_03",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Global Tech Titan",
    title: "Group C — Buzzer Clue 3",
    prompt: "BUZZ IN! Connect: Tesla electric supercar, Falcon 9 orbital rocket, Starlink satellite constellation, X app.",
    clues: [
      { id: 1, label: "Clue 1: Electric vehicle lithium battery & futuristic Cybertruck", url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Reusable orbital space rocket booster landing on ocean drone ship", url: "https://images.unsplash.com/photo-1517976487502-588383a8b27f?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Elon Musk",
    aliases: ["elon musk", "musk", "tesla", "spacex"],
    points: 20,
    penalty: 5,
    explanation: "Elon Musk heads Tesla, SpaceX, and X, pioneering electric vehicles, reusable space rockets, and satellite internet."
  },
  {
    id: "r2_gc_04",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Literary Politician",
    title: "Group C — Buzzer Clue 4",
    prompt: "BUZZ IN! Connect: 'Kalaignar', Dark sunglasses & yellow shawl, Parasakthi fiery court monologues, 5-time CM.",
    clues: [
      { id: 1, label: "Clue 1: Rectangular dark black sunglasses & bright yellow shoulder shawl", url: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Quill pen writing poetic Tamil scripts for historic cinema classics", url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "M. Karunanidhi",
    aliases: ["karunanidhi", "kalaignar", "m karunanidhi", "kalaignar karunanidhi"],
    points: 20,
    penalty: 5,
    explanation: "M. Karunanidhi (Kalaignar) was a master orator, scriptwriter of Parasakthi, and 5-time Chief Minister of Tamil Nadu who led the DMK for five decades."
  },
  {
    id: "r2_gc_05",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Cult Masterpiece",
    title: "Group C — Buzzer Clue 5",
    prompt: "BUZZ IN! Connect: Nalla Sivam scarred communist, Ad commercial director Anbarasu, Train journey, 'Love is God'.",
    clues: [
      { id: 1, label: "Clue 1: Red street-theatre flag & scarred face with dark thick spectacles", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Heavy rainy railway platform & tea glass shared between strangers", url: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Anbe Sivam",
    aliases: ["anbe sivam", "nalla sivam", "kamal anbe sivam", "anbe shivam"],
    points: 20,
    penalty: 5,
    explanation: "Anbe Sivam (2003) starring Kamal Haasan and R. Madhavan is regarded as one of Indian cinema's greatest humanist classics."
  },
  {
    id: "r2_gc_06",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Mountain Paradise",
    title: "Group C — Buzzer Clue 6",
    prompt: "BUZZ IN! Connect: Blue Nilgiri Toy Train, Terraced green tea estates, Doddabetta Peak, Queen of Hill Stations.",
    clues: [
      { id: 1, label: "Clue 1: Blue mountain heritage steam rack railway locomotive winding through tunnels", url: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Lush rolling emerald tea plantations veiled in misty cool morning clouds", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Ooty",
    aliases: ["ooty", "udhagamandalam", "nilgiris", "queen of hill stations"],
    points: 20,
    penalty: 5,
    explanation: "Ooty (Udhagamandalam) in the Nilgiri Hills is the celebrated 'Queen of Hill Stations', famed for its UNESCO toy train, botanical gardens, and tea."
  },
  {
    id: "r2_gc_07",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Music Icon",
    title: "Group C — Buzzer Clue 7",
    prompt: "BUZZ IN! Connect: 'Vaseegara' debut, Catchy gibberish humming intros ('O Maha Zeeya'), Gautham Menon police love tracks.",
    clues: [
      { id: 1, label: "Clue 1: Studio electric guitar chord with smooth acoustic reverb", url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Police sunglasses and breezy beach romance scene", url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Harris Jayaraj",
    aliases: ["harris jayaraj", "harris", "hj", "harris maam"],
    points: 20,
    penalty: 5,
    explanation: "Harris Jayaraj debuted with Minnale and scored era-defining albums including Kaakha Kaakha, Anniyan, Ghajini, and Vettaiyaadu Vilaiyaadu."
  },
  {
    id: "r2_gc_08",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Cultural Spectacle",
    title: "Group C — Buzzer Clue 8",
    prompt: "BUZZ IN! Connect: River Vaigai entry, Lord Kallazhagar riding golden horse, Millions in green silk attire.",
    clues: [
      { id: 1, label: "Clue 1: A majestic golden horse idol carrying a decorated deity into river water", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Ocean of millions of devotees spraying scented water in summer sun", url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Chithirai Thiruvizha",
    aliases: ["chithirai thiruvizha", "kallazhagar thiruvizha", "chithirai festival", "vaigai azhagar"],
    points: 20,
    penalty: 5,
    explanation: "Madurai Chithirai Thiruvizha attracts over a million pilgrims to witness Lord Kallazhagar's grand descent into the Vaigai River."
  },
  {
    id: "r2_gc_09",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Tamil Gangster Cult",
    title: "Group C — Buzzer Clue 9",
    prompt: "BUZZ IN! Connect: Carrom board champion Anbu, Vetrimaaran & Dhanush, Rajan lighthouse legacy, North Madras.",
    clues: [
      { id: 1, label: "Clue 1: Wooden carrom board striker aiming for white coins in a narrow room", url: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Sea harbor cargo containers & fishing boats of Royapuram", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Vada Chennai",
    aliases: ["vada chennai", "vetrimaaran vada chennai", "dhanush vada chennai", "vadachennai"],
    points: 20,
    penalty: 5,
    explanation: "Vetrimaaran's Vada Chennai (2018) starring Dhanush depicts the generational political and carrom subculture of North Madras."
  },
  {
    id: "r2_gc_10",
    round: 2,
    group: "C",
    type: "buzzer",
    tamilCategory: "Global Cricket Icon",
    title: "Group C — Buzzer Clue 10",
    prompt: "BUZZ IN! Connect: Jersey #18, Aggressive fist-pump celebration, 50 ODI centuries beating Tendulkar, 'King'.",
    clues: [
      { id: 1, label: "Clue 1: Navy blue Team India cricket jersey with #18 on the back", url: "https://images.unsplash.com/photo-1526676037777-05a232554f77?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Cricket bat raised to the sky acknowledging 50th century record in World Cup", url: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Virat Kohli",
    aliases: ["virat kohli", "kohli", "king kohli", "virat"],
    points: 20,
    penalty: 5,
    explanation: "Virat Kohli is world cricket's run-machine who surpassed Sachin Tendulkar's world record by hitting 50 ODI centuries."
  },

  // =========================================================================
  // ROUND 3: GRAND FINALS BUZZER BATTLE (20 High-Stakes Championship Questions)
  // 10 Core + 10 Backup • Correct +30 / +40 pts, Wrong -10 / -15 pts
  // =========================================================================

  // ------------------------- FINALS CORE (10 Questions) -------------------------
  {
    id: "r3_fin_01",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Cinema Legend",
    title: "Grand Finale — Question 1: Thalaivar",
    prompt: "FINAL BUZZER! Connect: Sunglasses glass flick, Baashha auto rickshaw badge, Dadasaheb Phalke award, 'En vazhi thani vazhi'.",
    clues: [
      { id: 1, label: "Clue 1: Dark sunglasses flicked in mid-air with lightning speed", url: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Yellow & black auto rickshaw driver uniform (#B-12)", url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: National Dadasaheb Phalke Award trophy & roaring cinema fans", url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Superstar Rajinikanth",
    aliases: ["rajinikanth", "rajini", "superstar", "thalaivar", "superstar rajinikanth", "shivaji rao gaekwad"],
    points: 30,
    penalty: 10,
    explanation: "Superstar Rajinikanth is Indian cinema's biggest cultural icon with enduring classics like Baashha, Annamalai, Sivaji, and Jailer."
  },
  {
    id: "r3_fin_02",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Master Director",
    title: "Grand Finale — Question 2: The Auteur",
    prompt: "FINAL BUZZER! Connect: Nayakan in Bombay, Thalapathi friendship, Alaipayuthey train romance, Ponniyin Selvan epic.",
    clues: [
      { id: 1, label: "Clue 1: Velu Nayakar vintage white dhoti & umbrella in rain", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Sub-urban passenger train compartment & mirror reflection", url: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Madras Talkies banner & historical Chola kingdom palace", url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Mani Ratnam",
    aliases: ["mani ratnam", "maniratnam", "director mani ratnam", "gopala ratnam subramaniam"],
    points: 30,
    penalty: 10,
    explanation: "Mani Ratnam reshaped Indian visual storytelling with masterpieces like Mouna Ragam, Nayakan, Thalapathi, Iruvar, and Ponniyin Selvan."
  },
  {
    id: "r3_fin_03",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Box Office King",
    title: "Grand Finale — Question 3: Thalapathy",
    prompt: "FINAL BUZZER! Connect: Ghilli kabaddi jersey, Thuppakki army dog tags, Master chalkboard, GOAT double-action, TVK political flag.",
    clues: [
      { id: 1, label: "Clue 1: Kabaddi sports jersey #7 & captain armband", url: "https://images.unsplash.com/photo-1526676037777-05a232554f77?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Military captain identity dog tag & 12 coin sleeper cell puzzle", url: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Sea of millions of chanting fans ('En Nenjil Kudi Irukkum...')", url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Thalapathy Vijay",
    aliases: ["vijay", "thalapathy vijay", "thalapathy", "joseph vijay", "actor vijay"],
    points: 30,
    penalty: 10,
    explanation: "Thalapathy Vijay is Kollywood's box-office titan with historic hits including Ghilli, Thuppakki, Mersal, Master, Leo, and GOAT."
  },
  {
    id: "r3_fin_04",
    round: 3,
    type: "buzzer",
    tamilCategory: "Global Sports Legend",
    title: "Grand Finale — Championship Decider: The Greatest of All Time",
    prompt: "FINAL DECIDER! Connect: Iconic #7 jersey, Airborne 'SIUUU' celebration, 5 Champions League crowns, 900+ career goals.",
    clues: [
      { id: 1, label: "Clue 1: Football jersey with legendary number 7", url: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: High leap in the air with arms outstretched ('SIUUU!')", url: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Five European Golden Ball trophies & world scoring record", url: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Cristiano Ronaldo",
    aliases: ["cristiano ronaldo", "ronaldo", "cr7", "cristiano"],
    points: 40,
    penalty: 15,
    explanation: "Cristiano Ronaldo (CR7) is the highest goalscorer in football history, an idol to millions of sports lovers across Tamil Nadu and the globe!"
  },
  {
    id: "r3_fin_05",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Cinema Legend",
    title: "Grand Finale — Question 5: Ulaganayagan",
    prompt: "FINAL BUZZER! Connect: 10 unique avatars in Dasavathaaram, Nayakan Velu Nayakar, Hey Ram, Vikram 2022 Ghost.",
    clues: [
      { id: 1, label: "Clue 1: Prosthetic makeup case transforming into 10 characters", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: 4 National Film Awards & Padma Bhushan medal", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Iconic film production house roaring lion banner emblem", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Kamal Haasan",
    aliases: ["kamal haasan", "kamal", "ulaganayagan", "kamalhasan", "ulaganayagan kamal haasan"],
    points: 30,
    penalty: 10,
    explanation: "Kamal Haasan (Ulaganayagan) is one of world cinema's most versatile actors, writers, and directors with legendary works spanning six decades."
  },
  {
    id: "r3_fin_06",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Political Icon",
    title: "Grand Finale — Question 6: Puratchi Thalaivi",
    prompt: "FINAL BUZZER! Connect: Green silk saree & cape, 1-rupee Amma Canteen idlis, Poes Garden Veda Nilayam, 6-time CM.",
    clues: [
      { id: 1, label: "Clue 1: Regal emerald green saree with matching shawl cloak", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Steaming hot subsidized 1-rupee idlis in stainless steel plates (Amma Unavagam)", url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Chepauk Secretariat Chief Minister assembly chair", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "J. Jayalalithaa",
    aliases: ["jayalalithaa", "amma", "puratchi thalaivi", "j jayalalithaa", "jayalalitha"],
    points: 30,
    penalty: 10,
    explanation: "Puratchi Thalaivi J. Jayalalithaa served as Chief Minister of Tamil Nadu six times, pioneering welfare models like Amma Canteens and Cradle Baby scheme."
  },
  {
    id: "r3_fin_07",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Sports Pride",
    title: "Grand Finale — Question 7: Namma Thala",
    prompt: "FINAL BUZZER! Connect: CSK bright canary yellow jersey #7, Chepauk stadium roar, Helicopter shot, 5 IPL trophies.",
    clues: [
      { id: 1, label: "Clue 1: Chennai Super Kings canary yellow jersey #7 with roaring lion crest", url: "https://images.unsplash.com/photo-1526676037777-05a232554f77?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Whistle Podu yellow flags waving across MA Chidambaram Stadium", url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Lightning stump stumping glove reflexes behind the wickets", url: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "MS Dhoni",
    aliases: ["ms dhoni", "dhoni", "thala dhoni", "msd", "csk dhoni", "mahendra singh dhoni"],
    points: 30,
    penalty: 10,
    explanation: "MS Dhoni is revered as Chennai's adopted son ('Thala'), leading Chennai Super Kings to a record-tying 5 IPL titles."
  },
  {
    id: "r3_fin_08",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Statesman & Scholar",
    title: "Grand Finale — Question 8: Arignar Anna",
    prompt: "FINAL BUZZER! Connect: Conjeevaram scholar, Renaming Madras State to Tamil Nadu (1969), Two-language formula, DMK founder.",
    clues: [
      { id: 1, label: "Clue 1: Vintage black-rimmed reading spectacles & orator podium", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Fort St. George resolution renaming Madras State to 'Tamil Nadu'", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: 'Kadamai, Kanniyam, Kattupaadu' golden political motto", url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "C. N. Annadurai",
    aliases: ["anna", "arignar anna", "cn annadurai", "c n annadurai", "annadurai"],
    points: 30,
    penalty: 10,
    explanation: "Arignar Anna founded the DMK and became Chief Minister in 1967, officially naming the state 'Tamil Nadu' and legalizing Self-Respect marriages."
  },
  {
    id: "r3_fin_09",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Sci-Fi Cult",
    title: "Grand Finale — Question 9: The Time Watch",
    prompt: "FINAL BUZZER! Connect: Time-traveling wrist watch, Suriya triple role, Villain Athreya in wheelchair, AR Rahman music.",
    clues: [
      { id: 1, label: "Clue 1: Intricate golden steampunk wrist watch with a miniature key turning time back", url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Wheelchair-bound menacing villain tapping a golden cane (Athreya)", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Freezing water droplets and paused raindrops suspended in mid-air", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "24",
    aliases: ["24", "24 movie", "athreya 24", "suriya 24", "watch 24"],
    points: 30,
    penalty: 10,
    explanation: "24 (2016), directed by Vikram Kumar, starred Suriya in three roles (Mani, Sethuraman, and Athreya) centered around a 24-hour time machine watch."
  },
  {
    id: "r3_fin_10",
    round: 3,
    type: "buzzer",
    tamilCategory: "Tamil Grand Director",
    title: "Grand Finale — Question 10: The Showman",
    prompt: "FINAL BUZZER! Connect: Indian grandfather Varma Kalai martial art, Anniyan Garuda Puranam punishments, Robot Chitti 2.0.",
    clues: [
      { id: 1, label: "Clue 1: Ancient nerve pressure point martial art (Varma Kalai)", url: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Futuristic humanoid android robot with laser optics (Chitti 2.0)", url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Grand stadium song sets and cutting-edge visual CGI effects", url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "S. Shankar",
    aliases: ["shankar", "director shankar", "s shankar", "s. shankar"],
    points: 30,
    penalty: 10,
    explanation: "Director S. Shankar is renowned for his mega-budget visual spectacles and vigilante epics including Gentleman, Indian, Anniyan, Sivaji, and Enthiran."
  },

  // ------------------------- FINALS BACKUP (10 Questions) -------------------------
  {
    id: "r3_fin_11",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Cinema Megastar",
    title: "Finals Backup — Question 11: Ultimate Star",
    prompt: "FINAL BUZZER! Connect: 1000cc racing superbike helmet, Aeromodelling UAV drone pilot, Billa white suit, Thala.",
    clues: [
      { id: 1, label: "Clue 1: Professional motorcycle racing helmet & track leather suit", url: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Remote controlled drone quadcopter & aeromodelling workshop", url: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Crisp white gangster blazer & twin handguns (Billa)", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Ajith Kumar",
    aliases: ["ajith kumar", "ajith", "thala", "thala ajith", "ak"],
    points: 30,
    penalty: 10,
    explanation: "Ajith Kumar (AK / Thala) is one of Tamil cinema's biggest superstars, also an international motor racer, rifle shooter, and drone researcher."
  },
  {
    id: "r3_fin_12",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Versatile Star",
    title: "Finals Backup — Question 12: National Award Champion",
    prompt: "FINAL BUZZER! Connect: Asuran sickle fight, Aadukalam rooster fight National Award, Hollywood assassin The Gray Man, Wunderbar.",
    clues: [
      { id: 1, label: "Clue 1: Battle-worn sickle & bloodied soil of Kovilpatti (Asuran)", url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Champion Madurai fighting rooster with sharp leg spurs (Aadukalam)", url: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Hollywood black tuxedo suit with twin daggers (Avik San / The Gray Man)", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Dhanush",
    aliases: ["dhanush", "actor dhanush", "d", "asuran dhanush"],
    points: 30,
    penalty: 10,
    explanation: "Dhanush won multiple National Film Awards for Best Actor in Aadukalam and Asuran, and starred in Hollywood's The Gray Man and Bollywood's Raanjhanaa."
  },
  {
    id: "r3_fin_13",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Cinema Phenomenon",
    title: "Finals Backup — Question 13: Makkal Selvan",
    prompt: "FINAL BUZZER! Connect: Super Deluxe Shilpa, Vikram Vedha gangster Vedha, Master Bhavani, 50th film Maharaja dustbin puzzle.",
    clues: [
      { id: 1, label: "Clue 1: Saree-clad Shilpa avatar & red lipstick (Super Deluxe)", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Salt & pepper beard gangster flipping a coin ('Oru kadha sollatuma?')", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Old metal dustbin (Lakshmi) reported missing to police (Maharaja)", url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Vijay Sethupathi",
    aliases: ["vijay sethupathi", "vjs", "makkal selvan", "sethupathi"],
    points: 30,
    penalty: 10,
    explanation: "Vijay Sethupathi (Makkal Selvan) is revered for natural acting across films like Pizza, Vikram Vedha, 96, Super Deluxe, and his 50th hit Maharaja."
  },
  {
    id: "r3_fin_14",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Star & Philanthropist",
    title: "Finals Backup — Question 14: The Fighter for Justice",
    prompt: "FINAL BUZZER! Connect: Soorarai Pottru 1-rupee Deccan airline, Jai Bhim human rights lawyer, Rolex cameo in Vikram, Agaram Foundation.",
    clues: [
      { id: 1, label: "Clue 1: Commercial passenger jet aircraft flying low over Deccan village", url: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Black advocate coat & legal constitution book (Advocate Chandru in Jai Bhim)", url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Brutal gold Rolex watch & curved meat cleaver machete", url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Suriya",
    aliases: ["suriya", "surya", "actor suriya", "saravanan sivakumar"],
    points: 30,
    penalty: 10,
    explanation: "Suriya won the National Award for Soorarai Pottru, starred in the globally acclaimed Jai Bhim, and educates thousands through the Agaram Foundation."
  },
  {
    id: "r3_fin_15",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Cinema Auteur",
    title: "Finals Backup — Question 15: Master of Raw Realism",
    prompt: "FINAL BUZZER! Connect: Polladhavan Pulsar bike, Aadukalam roosters, Asuran oppressed rage, Viduthalai forest police thriller.",
    clues: [
      { id: 1, label: "Clue 1: Black Bajaj Pulsar motorcycle standing under street lamp (Polladhavan)", url: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Deep green dense rainforest mountains & train bridge explosion (Viduthalai)", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: National Film Award for Best Director & golden screenplay trophy", url: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Vetrimaaran",
    aliases: ["vetrimaaran", "vetrimaran", "director vetrimaaran", "vetri maaran"],
    points: 30,
    penalty: 10,
    explanation: "Vetrimaaran is celebrated for his hard-hitting, literature-based cinema including Polladhavan, Aadukalam, Visaranai, Vada Chennai, Asuran, and Viduthalai."
  },
  {
    id: "r3_fin_16",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Imperial Emperor",
    title: "Finals Backup — Question 16: King of Kings",
    prompt: "FINAL BUZZER! Connect: 'Arulmozhivarman', Building the Big Temple of Thanjavur, Blue naval fleet commanding the Bay of Bengal, Golden Chola Tiger.",
    clues: [
      { id: 1, label: "Clue 1: Imperial majestic naval warships dominating the Bay of Bengal", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: The soaring 216-foot granite Vimana tower of Thanjavur Big Temple", url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Imperial coronation crown and copper plate land revenue grants", url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Raja Raja Chola I",
    aliases: ["raja raja chola", "rajaraja cholan", "raja raja chola i", "rajarajan", "arulmozhivarman"],
    points: 30,
    penalty: 10,
    explanation: "Raja Raja Chola I (reigned 985–1014 CE) was the greatest emperor of the Chola Dynasty, builder of the Brihadisvara Temple, and creator of a powerful maritime empire."
  },
  {
    id: "r3_fin_17",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Gaana King",
    title: "Finals Backup — Question 17: Thenisai Thendral",
    prompt: "FINAL BUZZER! Connect: Madras Gaana folk beats, Baashha 'Naan Autokaaran', Annamalai theme, Kasethan Kadavulada.",
    clues: [
      { id: 1, label: "Clue 1: Traditional Dappankuthu percussion drum & brass cymbals", url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Chennai yellow auto meter & passenger horn ('Auto Kaaran')", url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Audio cassette stamped 'Thenisai Thendral'", url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Deva",
    aliases: ["deva", "thenisai thendral", "thenisai thendral deva", "gaana deva"],
    points: 30,
    penalty: 10,
    explanation: "Deva (Thenisai Thendral) brought North Chennai Gaana folk music to mainstream cinema, composing legendary soundtracks for Baashha, Annamalai, and Basha."
  },
  {
    id: "r3_fin_18",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Sports Prodigy",
    title: "Finals Backup — Question 18: Chess Sensation",
    prompt: "FINAL BUZZER! Connect: Defeating World Champion Magnus Carlsen at age 16, FIDE World Cup 2023 finalist in Baku, Sister GM Vaishali.",
    clues: [
      { id: 1, label: "Clue 1: Chess digital tournament clock ticking in rapid tiebreak", url: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Silver medal trophy at FIDE World Cup 2023 in Baku", url: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Chennai sibling duo both holding Grandmaster titles with mother Nagalakshmi", url: "https://images.unsplash.com/photo-1586165368502-1bad197a6461?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "R. Praggnanandhaa",
    aliases: ["praggnanandhaa", "r praggnanandhaa", "pragg", "praggnananda"],
    points: 30,
    penalty: 10,
    explanation: "R. Praggnanandhaa became a world sensation after beating Magnus Carlsen multiple times and reaching the 2023 FIDE World Cup Final alongside his GM sister Vaishali."
  },
  {
    id: "r3_fin_19",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Tamil Sweet Heritage",
    title: "Finals Backup — Question 19: The Crunchy Candy of Kovilpatti",
    prompt: "FINAL BUZZER! Connect: Kovilpatti GI tag, Roasted crunchy groundnuts, Organic sugarcane jaggery syrup, Traditional sweet snack.",
    clues: [
      { id: 1, label: "Clue 1: Golden roasted peanuts split into halves", url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Bubbling copper vat of molten dark jaggery syrup (Vellam)", url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: Square cut glossy nut brittle candy slabs with colorful shredded coconut ribbon", url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Kovilpatti Kadalai Mittai",
    aliases: ["kadalai mittai", "kovilpatti kadalai mittai", "peanut candy", "kovilpatti peanut candy"],
    points: 30,
    penalty: 10,
    explanation: "Kovilpatti Kadalai Mittai earned a Geographical Indication (GI) tag for its distinctive recipe blending roasted groundnuts with organic jaggery syrup and local water."
  },
  {
    id: "r3_fin_20",
    round: 3,
    isBackup: true,
    type: "buzzer",
    tamilCategory: "Global Superhero (20% World)",
    title: "Finals Backup — Question 20: The Friendly Neighborhood Hero",
    prompt: "FINAL BUZZER! Connect: Radioactive spider bite, Red & blue web suit, 'With great power comes great responsibility', Peter Parker.",
    clues: [
      { id: 1, label: "Clue 1: Intricate silk web glistening across towering skyscraper glass", url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80" },
      { id: 2, label: "Clue 2: Red and cobalt blue masked suit swinging between high-rise buildings", url: "https://images.unsplash.com/photo-1517976487502-588383a8b27f?w=800&auto=format&fit=crop&q=80" },
      { id: 3, label: "Clue 3: High school student with SLR camera working for the Daily Bugle", url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80" },
    ],
    correctAnswer: "Spider-Man",
    aliases: ["spider-man", "spiderman", "peter parker", "friendly neighborhood spider-man"],
    points: 30,
    penalty: 10,
    explanation: "Spider-Man (Peter Parker) is Marvel's beloved flagship hero taught by Uncle Ben that 'With great power comes great responsibility'."
  }
];